theme: jekyll-theme-hacker
title: Greg Roberge's ePortfolio test
url: /

title: Code Review
url:/CodeReview.html

title: Software Design
url:https://groberge.github.io/SoftwareDesign.html

# --- List of links in the navigation bar --- #

navbar-links:
  Home: "index"
  Code Review: "CodeReview"
  Software Design: "SoftwareDesign"
  Data Structures and Algorithms: "DataStructures"
  Databases: "Databases"
