theme: jekyll-theme-hacker
title: Greg Roberge's ePortfolio


# --- List of links in the navigation bar --- #

navbar-links:
  Home: "https://groberge.github.io"
  Code Review: "https://groberge.github.io/CodeReview.html"
  Software Design: "https://groberge.github.io/SoftwareDesign.html"
  Data Structures and Algorithms: "https://groberge.github.io/DataStructures.html"
  Databases: "https://groberge.github.io/Databases.html"
