theme: jekyll-theme-hacker
title: Greg Roberge's ePortfolio

title: Code Review
url: "https://groberge.github.io/CodeReview.html"

title: Software Design and Engineering
url: "SoftwareDesign.html"

title: Data Structures and Algorithms
url: "DataStructures.html"

title: Databases
url: "Databases.html"

title: Another

# --- List of links in the navigation bar --- #

navbar-links:
  Home: "https://groberge.github.io"
  Code Review: "https://groberge.github.io/CodeReview.html"
  Software Design: "https://groberge.github.io/SoftwareDesign.html"
  Data Structures and Algorithms: "https://groberge.github.io/DataStructures.html"
  Databases: "https://groberge.github.io/Databases.html"
