theme: jekyll-theme-hacker
title: Greg Roberge's ePortfolio

<nav>
  <ul>
    <li><a href="index.html">Home</a></li>
    <li><a href="CodeReview.html">Code Review</a></li>
    <li><a href="SoftwareDesign.html">Software Design</a></li>
  </ul>
</nav>

# --- List of links in the navigation bar --- #

navbar-links:
  Home: "index"
  Code Review: "CodeReview"
  Software Design: "SoftwareDesign"
  Data Structures and Algorithms: "DataStructures"
  Databases: "Databases"
